from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class Block:
    """One named section of a prompt.

    The content is a literal string. Any XML-style wrapping tags like
    `<role>...</role>` are part of the content, not auto-generated by the
    renderer, so variant overrides can replace the block wholesale.
    """

    name: str
    content: str


@dataclass(frozen=True, slots=True)
class PromptSpec:
    """A declarative description of one prompt.

    The renderer joins blocks with a blank line and substitutes `${var}`
    placeholders from caller-supplied keyword arguments. The `variables`
    field is the declared set of placeholders, used to detect missing or
    unknown inputs at render time.
    """

    id: str
    version: str
    blocks: tuple[Block, ...]
    variables: frozenset[str] = field(default_factory=frozenset)
