name: CI

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
        with:
          enable-cache: true

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          allow-prereleases: true

      - run: uv sync --frozen

      - run: make check

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: streetsidesoftware/cspell-action@v8
        with:
          files: 'docs/**/*.md'

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
        with:
          enable-cache: true

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          allow-prereleases: true

      - run: uv sync --frozen

      - run: make docs
