name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
        with:
          enable-cache: true

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          allow-prereleases: true

      - run: uv build

      - uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@cec208311dfd045dd5311c1add060b2062131d57
        with:
          name: dist
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1
